# Generated by Django 3.1.7 on 2021-04-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jwt',
            options={'verbose_name_plural': 'Tokens'},
        ),
    ]
