# Generated by Django 3.1.7 on 2021-04-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Sizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField()),
                ('litre_number', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Gas Sizes',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Reference_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
