# Generated by Django 3.1.7 on 2021-04-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_vendor_shop_phone_number'),
        ('transaction', '0002_auto_20210421_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_cost_per_km',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Delivery Unit price/Km',
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='item_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='overall_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transportation_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transporter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendor', to='user.vendor_shop'),
        ),
    ]
