# Generated by Django 3.1.7 on 2021-04-30 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0004_auto_20210430_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_name', models.CharField(max_length=100, null=True)),
                ('card_number', models.IntegerField()),
                ('customer_CVV', models.IntegerField()),
                ('expiry_date', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_card_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Card Details',
            },
        ),
    ]
