# Generated by Django 3.1.7 on 2021-04-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_card_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_details',
            old_name='Card_name',
            new_name='card_name',
        ),
    ]
