# Generated by Django 3.1.7 on 2021-04-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210430_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_details',
            old_name='customer_CVV',
            new_name='CVV',
        ),
    ]
