# Generated by Django 3.1.7 on 2021-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20210430_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='overall_cost',
        ),
    ]
