# Generated by Django 3.1.7 on 2021-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_remove_purchase_overall_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_details',
            name='card_name',
        ),
        migrations.AddField(
            model_name='card_details',
            name='card_type',
            field=models.CharField(choices=[('Mastercard', 'Mastercard'), ('Visa', 'Visa'), ('Verve', 'Verve')], max_length=20, null=True),
        ),
    ]
