# Generated by Django 3.1.7 on 2021-05-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_auto_20210501_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_details',
            name='card_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
