# Generated by Django 3.1.7 on 2021-05-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20210501_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_details',
            name='user',
        ),
    ]
