# Generated by Django 3.1.7 on 2021-05-01 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0014_remove_card_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_card_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
