# Generated by Django 3.2.1 on 2021-05-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_card_details_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='customer_completed',
            new_name='transaction_completed',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='transporter_completed',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_completed',
        ),
    ]
