# Generated by Django 3.2.1 on 2021-05-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_auto_20210506_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='distance',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
