# Generated by Django 3.2.1 on 2021-05-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_vendor_shop_user_type'),
        ('transaction', '0018_auto_20210509_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='vendor_id',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vendor', to='user.vendor_shop'),
        ),
    ]
