# Generated by Django 3.2.1 on 2021-05-09 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0020_alter_purchase_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='transporter',
        ),
        migrations.AddField(
            model_name='purchase',
            name='accepted_vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transporter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Transporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
