# Generated by Django 3.2.1 on 2021-05-09 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0021_auto_20210509_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closest_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
