# Generated by Django 3.2.1 on 2021-05-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0023_auto_20210509_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='vendor_id',
            new_name='closest_vendor_id',
        ),
    ]
