# Generated by Django 3.2.1 on 2021-05-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_rename_vendor_id_purchase_closest_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_details',
            old_name='CVV',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='accepted_vendor_id',
            new_name='accepted_vendor',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='closest_vendor_id',
            new_name='closest_vendor',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='transporter_id',
            new_name='transporter',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Reference_id',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transporter_id',
            new_name='transporter',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
