# Generated by Django 3.2.1 on 2021-05-13 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_vendor_shop_user_type'),
        ('transaction', '0025_auto_20210509_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='vendor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vendor_name', to='user.vendor_shop'),
        ),
    ]
