# Generated by Django 3.2.1 on 2021-05-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_transporter'),
        ('transaction', '0026_alter_purchase_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transporter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.transporter'),
        ),
    ]
