# Generated by Django 3.1.7 on 2021-04-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210410_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='purchase_id',
        ),
    ]
