# Generated by Django 3.1.7 on 2021-04-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_transaction_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transporter_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor_id',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
