# Generated by Django 3.1.7 on 2021-04-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_vendorprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'verbose_name_plural': 'Vendor Profiles'},
        ),
    ]
