# Generated by Django 3.1.7 on 2021-04-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210421_1630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorProfile',
            new_name='Vendor_shop',
        ),
        migrations.AlterModelOptions(
            name='vendor_shop',
            options={'verbose_name_plural': 'Vendors'},
        ),
    ]
