# Generated by Django 3.1.7 on 2021-04-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210427_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_shop',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
