# Generated by Django 3.2.1 on 2021-05-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_vendor_shop_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
