# Generated by Django 3.2.1 on 2021-05-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_shop',
            name='user_type',
        ),
    ]
